CIRCUITPY_WIFI_SSID="RatPack"
CIRCUITPY_WIFI_PASSWORD="1baddad111"
CIRCUITPY_WEB_API_PASSWORD="a-super-secure-password"

AIRLABS_API_KEY="2bffd32d-660b-493d-85f6-c3f0f7e635b6"
MIN_LAT="39.5598865"
MIN_LON="-104.822308"
MAX_LAT="39.5029481"
MAX_LON="-104.7621859"